version: "3.9"

services:
  compose_api_service:
    build: ./api_service
    command: "poetry run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./api_service/:/code/
    ports:
      - 8001:8000
    depends_on:
      - compose_ml_service

  compose_ml_service:
    build: ./ml_service
    command: "poetry run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./ml_service/:/code/
    ports:
      - 8002:8000
