"""init db

Revision ID: 0ae31cfda61e
Revises: 
Create Date: 2023-04-10 17:28:56.276299

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ae31cfda61e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
