"""0003_add_first_name_to_user

Revision ID: 10bdcff62b53
Revises: f6e1d52a23e5
Create Date: 2023-04-10 18:22:51.144133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10bdcff62b53"
down_revision = "f6e1d52a23e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
